name: clem2itunes
base: core24
version: '0.1.3'
summary: Synchronise a remote Strawberry rated library to Music.app
description: |
  Crazy way to synchronise a remote Strawberry rated library with iTunes using
  Python, JXA and SSH.

  Requires the following packages on the source side:
  - id3ted

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: amd64
  arm64:
    build-on: arm64

apps:
  clem2itunes:
    command: bin/clem2itunes
    plugs:
      - home
      - network
      - network-bind
      - ssh-keys

parts:
  poetry-deps:
    plugin: nil
    override-build: |
      craftctl default
      curl -sSL https://install.python-poetry.org | PYTHONPYCACHEPREFIX=/tmp POETRY_HOME=${CRAFT_PART_INSTALL} python3 -
      env PYTHONPYCACHEPREFIX=/tmp ${CRAFT_PART_INSTALL}/bin/poetry self add poetry-plugin-export
  clem2itunes:
    after: [poetry-deps]
    plugin: poetry
    source: .
    stage-packages:
      - atomicparsley
      - mp3check
      - mp3splt
      - python3-venv
