apps:
  clem2itunes:
    command: 'bin/clem2itunes'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
      - 'ssh-keys'
base: 'core24'
confinement: 'strict'
description: 'Crazy way to synchronise a remote Strawberry rated library to Music.app using Python, JXA and SSH.'
grade: 'stable'
name: 'clem2itunes'
parts:
  clem2itunes:
    plugin: 'poetry'
    source: '.'
    stage-packages:
      - 'atomicparsley'
      - 'mp3check'
      - 'mp3splt'
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
summary: 'Synchronise a remote Strawberry rated library to Music.app'
version: '0.1.3'
