name: clem2itunes
base: core24
version: '0.1.3'
summary: Synchronise a remote Strawberry rated library to Music.app
description: |
  Crazy way to synchronise a remote Strawberry rated library with iTunes using
  Python, JXA and SSH.

  Requires the following packages on the source side:
  - AtomicParsley
  - id3ted
  - mp3check
  - mp3splt

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: amd64
  arm64:
    build-on: arm64

apps:
  clem2itunes:
    command: bin/clem2itunes
    plugs:
      - home
      - network
      - network-bind
      - ssh-keys

parts:
  clem2itunes:
    plugin: poetry
    source: .
    poetry-with:
      - pip
    stage-packages:
      - atomicparsley
      - mp3check
      - mp3splt
      - python3-venv
