apps:
  clem2itunes:
    command: 'bin/clem2itunes'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
      - 'ssh-keys'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/clem2itunes/issues'
description: 'Crazy way to synchronise a remote Strawberry rated library to Music.app using Python, JXA and SSH.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/clem2itunes/issues'
license: 'MIT'
name: 'clem2itunes'
parts:
  clem2itunes:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages:
      - 'atomicparsley'
      - 'mp3check'
      - 'mp3splt'
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/clem2itunes'
summary: 'Synchronise a remote Strawberry rated library to Music.app'
title: 'clem2itunes'
version: '0.1.3'
website: 'https://tatsh.github.io/clem2itunes/'
